routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|oks
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
	
	//cuti
	Route::get('cutis/report', 'CutiController@reportCuti')->name('reportCuti');
	Route::get('cutis/updatecuti', 'CutiController@updateCuti');
	Route::get('cutis/{cuti}/view', ['as' => 'view/cuti', 'uses' => 'CutiController@view']);
	Route::post('cutis/status', ['as' => 'status/cuti', 'uses' => 'CutiController@status']);
	Route::get('cutis/{cuti}/letter', ['as' => 'letter/cuti', 'uses' => 'CutiController@letter']);
	
	//eprescribings
	Route::get('eprescribings/{id}/history/{no_reg?}', 'EprescribingController@history')->name('historyEprescribing');
	Route::get('eprescribings/{id}/order/{no_order?}', 'EprescribingController@create')->name('orderEprescribing');
	Route::post('eprescribings/{id}/order/{no_order?}', 'EprescribingController@store')->name('orderEprescribing');
	
	//HAIs
	Route::get('hais/report', 'HaisController@reportHais')->name('reportHais');
	
	//resource
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
	Route::resource('comments', 'CommentController');
	Route::resource('cutis', 'CutiController');
	Route::resource('eprescribings', 'EprescribingController');
	Route::resource('hais', 'HaisController');
	//Route::resource('masters', 'MasterController');
	
	//add new
	Route::get('/', 'HomeController@index')->name('home');
});

//without Auth
Route::get('/home', 'HomeController@index')->name('home');
Route::get('cutis/{cuti}/approval', ['as' => 'approval/cuti', 'uses' => 'CutiController@approval']);

//Request is Ajax
Route::get('getBagian',['as'=>'getBagian','uses'=>'AjaxController@getBagian']);
Route::get('getSubagSeksi',['as'=>'getSubagSeksi','uses'=>'AjaxController@getSubagSeksi']);
Route::get('getInstalasi',['as'=>'getInstalasi','uses'=>'AjaxController@getInstalasi']);
Route::get('getBarangFarmasi',['as'=>'getBarangFarmasi','uses'=>'AjaxController@getBarangFarmasi']);
Route::get('getDataPasien',['as'=>'getDataPasien','uses'=>'AjaxController@getDataPasien']);
Route::get('getICD',['as'=>'getICD','uses'=>'AjaxController@getICD']);
Route::get('getDataHAIs',['as'=>'getDataHAIs','uses'=>'AjaxController@getDataHAIs']);

//DataTables
Route::post('getDataCuti',['as'=>'getDataCuti','uses'=>'DataTablesController@getDataCuti']);
Route::post('getReportHais',['as'=>'getReportHais','uses'=>'DataTablesController@getReportHais']);
Route::post('getDataUser',['as'=>'getDataUser','uses'=>'DataTablesController@getDataUser']);

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')
@section('content')
		<!--<div class="row tile_count">
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total Cuti {{ Request::segment(3) }}</span>
              <div class="count">18</div>
              <span class="count_bottom"><i class="green">4% </i> From last Week</span>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-clock-o"></i> Sisa Cuti {{ date('Y') }}</span>
              <div class="count">11</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Sisa Cuti {{ date('Y') }}</span>
              <div class="count green">7</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total Females</span>
              <div class="count">4,567</div>
              <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
              <div class="count">2,315</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
            <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
              <div class="count">7,325</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
        </div>-->
@endsection
<?php
/* 
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body text-center" style="margin-top: 4em">

                    <h1>
                        <svg xmlns="http://www.w3.org/2000/svg" width="84.1" height="57.6" viewBox="0 0 84.1 57.6"><path fill="#FB503B" d="M83.8 26.9c-.6-.6-8.3-10.3-9.6-11.9-1.4-1.6-2-1.3-2.9-1.2s-10.6 1.8-11.7 1.9c-1.1.2-1.8.6-1.1 1.6.6.9 7 9.9 8.4 12l-25.5 6.1L21.2 1.5c-.8-1.2-1-1.6-2.8-1.5C16.6.1 2.5 1.3 1.5 1.3c-1 .1-2.1.5-1.1 2.9S17.4 41 17.8 42c.4 1 1.6 2.6 4.3 2 2.8-.7 12.4-3.2 17.7-4.6 2.8 5 8.4 15.2 9.5 16.7 1.4 2 2.4 1.6 4.5 1 1.7-.5 26.2-9.3 27.3-9.8 1.1-.5 1.8-.8 1-1.9-.6-.8-7-9.5-10.4-14 2.3-.6 10.6-2.8 11.5-3.1 1-.3 1.2-.8.6-1.4zm-46.3 9.5c-.3.1-14.6 3.5-15.3 3.7-.8.2-.8.1-.8-.2-.2-.3-17-35.1-17.3-35.5-.2-.4-.2-.8 0-.8S17.6 2.4 18 2.4c.5 0 .4.1.6.4 0 0 18.7 32.3 19 32.8.4.5.2.7-.1.8zm40.2 7.5c.2.4.5.6-.3.8-.7.3-24.1 8.2-24.6 8.4-.5.2-.8.3-1.4-.6s-8.2-14-8.2-14L68.1 32c.6-.2.8-.3 1.2.3.4.7 8.2 11.3 8.4 11.6zm1.6-17.6c-.6.1-9.7 2.4-9.7 2.4l-7.5-10.2c-.2-.3-.4-.6.1-.7.5-.1 9-1.6 9.4-1.7.4-.1.7-.2 1.2.5.5.6 6.9 8.8 7.2 9.1.3.3-.1.5-.7.6z"></path></svg>
                    </h1>

                    <h3 class="modal-title">Complete Roles &amp; Permissions for Laravel 5.4</h3>

                    @role('Admin')
                    <h4>Visit <a href="{{ route('roles.index') }}">roles</a> and give permissions for each roles.</h4>
                    @endrole

                    <p>&nbsp;<br>
                    <p>Assign different <code>roles</code> to users and login from different browsers <br>
                        to see <code>access control</code> and <code>authorization</code> at work.</p>
                </div>
            </div>
        </div>
    </div>
@endsection 
*/
?>