routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|oks
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
	
	//cuti
	Route::get('cutis/report', 'CutiController@reportCuti')->name('reportCuti');
	Route::get('cutis/updatecuti', 'CutiController@updateCuti');
	Route::get('cutis/{cuti}/view', ['as' => 'view/cuti', 'uses' => 'CutiController@view']);
	Route::post('cutis/status', ['as' => 'status/cuti', 'uses' => 'CutiController@status']);
	Route::get('cutis/{cuti}/letter', ['as' => 'letter/cuti', 'uses' => 'CutiController@letter']);
	
	//eprescribings
	Route::get('eprescribings/{id}/history/{no_reg?}', 'EprescribingController@history')->name('historyEprescribing');
	Route::get('eprescribings/{id}/order/{no_order?}', 'EprescribingController@create')->name('orderEprescribing');
	Route::post('eprescribings/{id}/order/{no_order?}', 'EprescribingController@store')->name('orderEprescribing');
	
	//HAIs
	Route::get('hais/report', 'HaisController@reportHais')->name('reportHais');
	
	//resource
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
	Route::resource('comments', 'CommentController');
	Route::resource('cutis', 'CutiController');
	Route::resource('eprescribings', 'EprescribingController');
	Route::resource('hais', 'HaisController');
	//Route::resource('masters', 'MasterController');
	
	//add new
	Route::get('/', 'HomeController@index')->name('home');
});

//without Auth
Route::get('/home', 'HomeController@index')->name('home');
Route::get('cutis/{cuti}/approval', ['as' => 'approval/cuti', 'uses' => 'CutiController@approval']);

//Request is Ajax
Route::get('getBagian',['as'=>'getBagian','uses'=>'AjaxController@getBagian']);
Route::get('getSubagSeksi',['as'=>'getSubagSeksi','uses'=>'AjaxController@getSubagSeksi']);
Route::get('getInstalasi',['as'=>'getInstalasi','uses'=>'AjaxController@getInstalasi']);
Route::get('getBarangFarmasi',['as'=>'getBarangFarmasi','uses'=>'AjaxController@getBarangFarmasi']);
Route::get('getDataPasien',['as'=>'getDataPasien','uses'=>'AjaxController@getDataPasien']);
Route::get('getICD',['as'=>'getICD','uses'=>'AjaxController@getICD']);
Route::get('getDataHAIs',['as'=>'getDataHAIs','uses'=>'AjaxController@getDataHAIs']);

//DataTables
Route::post('getDataCuti',['as'=>'getDataCuti','uses'=>'DataTablesController@getDataCuti']);
Route::post('getReportHais',['as'=>'getReportHais','uses'=>'DataTablesController@getReportHais']);
Route::post('getDataUser',['as'=>'getDataUser','uses'=>'DataTablesController@getDataUser']);

app/Master.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Master extends Model
{
    protected $table = 'master';
	
    protected $fillable = ['name', 'description'];
}

app/Http/Controllers/MasterController.php
<?php

namespace App\Http\Controllers;

use App\Master;
use App\Cuti;
use Illuminate\Http\Request;

class MasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Master::get();
		
		return view('master.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('master._form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$this->validate($request, [
            'name' => 'required|min:5',
            'description' => 'required|min:5'
        ]);
		
        if(Master::create($request->all())){
			dd('ok');
		}else{
			dd('no');
		}
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Master  $master
     * @return \Illuminate\Http\Response
     */
    public function show(Master $master)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Master  $master
     * @return \Illuminate\Http\Response
     */
    public function edit(Master $master)
    {
		return view('master._form', compact('master'));
        //dd($master->toArray());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Master  $master
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Master $master)
    {
        $this->validate($request, [
            'name' => 'required|min:5',
            'description' => 'required|min:5'
        ]);
		
		if($master->update($request->all())){
			dd('ok');
		}else{
			dd('no');
		}
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Master  $master
     * @return \Illuminate\Http\Response
     */
    public function destroy(Master $master)
    {
        //
    }
}

resources/views/master/_form.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Form Master</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li style="float:right;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					
					<!-- CODE HERE -->
					<!-- {!! Form::open(['route' => ['masters.store'], 'class' => 'form-horizontal form-label-left' ]) !!} CREATE -->
					{!! Form::model($master, ['method' => 'PUT', 'route' => ['masters.update',  $master->id ], 'class' => 'form-horizontal form-label-left' ]) !!}
						<div class="form-group @if ($errors->has('name')) has-error @endif">
							{!! Html::decode(Form::label('name','Name <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
							<div class="col-md-6 col-sm-6 col-xs-12">
								{!! Form::text('name', null, ['class' => 'form-control col-md-7 col-xs-12']) !!}
							</div>
							@if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
						</div>
						<div class="form-group @if ($errors->has('description')) has-error @endif">
							{!! Html::decode(Form::label('description','Description <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
							<div class="col-md-6 col-sm-6 col-xs-12">
								{!! Form::textarea('description', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Keterangan Cuti', 'rows' => '4']) !!}
							</div>
							@if ($errors->has('description')) <p class="help-block">{{ $errors->first('description') }}</p> @endif
						</div>
						<!-- Submit Form Button -->
						<div class="ln_solid"></div>
						<div class="form-group">
							<div class="col-md-9 text-right">
								<a class="btn btn-danger" href="{{ route('cutis.index') }}">Cancel</a>
								{!! Form::submit('Create', ['class' => 'btn btn-success']) !!}
							</div>
						</div>
					{!! Form::close() !!}
					
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/master/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Form Master</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li style="float:right;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					
					<table>
						<tr>
							<td>Name</td>
							<td>Description</td>
						</tr>
						@if(!empty($data))
							@foreach($data as $val)
							<tr>
								<td>{{ $val->name }}</td>
								<td>{{ $val->description }}</td>
							</tr>
							@endforeach
						@endif
					</table>
					
				</div>
			</div>
		</div>
	</div>
@endsection