routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|oks
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group( ['middleware' => ['auth']], function() {
	
	//cuti
	Route::get('cutis/report', 'CutiController@reportCuti')->name('reportCuti');
	Route::get('cutis/updatecuti', 'CutiController@updateCuti');
	Route::get('cutis/{cuti}/view', ['as' => 'view/cuti', 'uses' => 'CutiController@view']);
	Route::post('cutis/status', ['as' => 'status/cuti', 'uses' => 'CutiController@status']);
	Route::get('cutis/{cuti}/letter', ['as' => 'letter/cuti', 'uses' => 'CutiController@letter']);
	
	//eprescribings
	Route::get('eprescribings/{id}/history/{no_reg?}', 'EprescribingController@history')->name('historyEprescribing');
	Route::get('eprescribings/{id}/order/{no_order?}', 'EprescribingController@create')->name('orderEprescribing');
	Route::post('eprescribings/{id}/order/{no_order?}', 'EprescribingController@store')->name('orderEprescribing');
	
	//HAIs
	Route::get('hais/report', 'HaisController@reportHais')->name('reportHais');
	
	//resource
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('posts', 'PostController');
	Route::resource('comments', 'CommentController');
	Route::resource('cutis', 'CutiController');
	Route::resource('eprescribings', 'EprescribingController');
	Route::resource('hais', 'HaisController');
	//Route::resource('masters', 'MasterController');
	
	//add new
	Route::get('/', 'HomeController@index')->name('home');
});

//without Auth
Route::get('/home', 'HomeController@index')->name('home');
Route::get('cutis/{cuti}/approval', ['as' => 'approval/cuti', 'uses' => 'CutiController@approval']);

//Request is Ajax
Route::get('getBagian',['as'=>'getBagian','uses'=>'AjaxController@getBagian']);
Route::get('getSubagSeksi',['as'=>'getSubagSeksi','uses'=>'AjaxController@getSubagSeksi']);
Route::get('getInstalasi',['as'=>'getInstalasi','uses'=>'AjaxController@getInstalasi']);
Route::get('getBarangFarmasi',['as'=>'getBarangFarmasi','uses'=>'AjaxController@getBarangFarmasi']);
Route::get('getDataPasien',['as'=>'getDataPasien','uses'=>'AjaxController@getDataPasien']);
Route::get('getICD',['as'=>'getICD','uses'=>'AjaxController@getICD']);
Route::get('getDataHAIs',['as'=>'getDataHAIs','uses'=>'AjaxController@getDataHAIs']);

//DataTables
Route::post('getDataCuti',['as'=>'getDataCuti','uses'=>'DataTablesController@getDataCuti']);
Route::post('getReportHais',['as'=>'getReportHais','uses'=>'DataTablesController@getReportHais']);
Route::post('getDataUser',['as'=>'getDataUser','uses'=>'DataTablesController@getDataUser']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\Traits\Uuid;

class User extends Authenticatable
{
    use Notifiable, HasRoles, Uuid;
	
	public $incrementing = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $casts = [
		'json_user' => 'array',
		'json_data' => 'array',
	];
	
    protected $fillable = [
        'id', 'name', 'nip', 'password', 'id_direktorat', 'id_bagian', 'id_subagseksi', 'id_instalasi', 'json_user', 'json_data'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
	
	public function instalasi()
    {
		$data = $this->belongsTo('App\Instalasi', 'id_instalasi', 'id');
		return $data;
    }
	
	public function subagseksi()
    {
		$data = $this->belongsTo('App\Subagseksi', 'id_subagseksi', 'id');
		return $data;
    }
	
	public function bagian()
    {
		$data = $this->belongsTo('App\Bagian', 'id_bagian', 'id');
		return $data;
    }
	
	public function direktorat()
    {
        $data = $this->belongsTo('App\GlobalParams', 'id_direktorat', 'sq_id');
		$data->getQuery()->where('xcond', 'direktorat');
		return $data;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\Permission;
use App\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    use Authorizable;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$roles = Role::pluck('name', 'id');	
		if(!Auth::user()->hasRole('Admin')) $roles = Role::whereNotIn('name', ['Admin'])->pluck('name', 'id');
        
        return view('user.new', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {

            $this->syncPermissions($request, $user);

            flash('User has been created.');

        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');

        return view('user.edit', compact('user', 'roles', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();

        flash()->success('User has been updated.');

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @internal param Request $request
     */
    public function destroy($id)
    {
        if ( Auth::user()->id == $id ) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect()->back();
    }

    /**
     * Sync roles and permissions
     *
     * @param Request $request
     * @param $user
     * @return string
     */
    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }
}

resources/views/user/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
	{!! Html::decode(Form::label('name','Name <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
	<div class="col-md-6 col-sm-6 col-xs-12">
		{!! Form::text('name', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Name']) !!}
	</div>
    @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Html::decode(Form::label('email','Email <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
	<div class="col-md-6 col-sm-6 col-xs-12">
		{!! Form::text('email', null, ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Email']) !!}
	</div>
    @if ($errors->has('email')) <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Html::decode(Form::label('password','Password <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
	<div class="col-md-6 col-sm-6 col-xs-12">
		{!! Form::text('password', '', ['class' => 'form-control col-md-7 col-xs-12', 'placeholder' => 'Password']) !!}
	</div>
    @if ($errors->has('password')) <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>

<!-- Roles Form Input -->
<div class="form-group @if ($errors->has('roles')) has-error @endif">
    {!! Html::decode(Form::label('roles[]', 'Roles <span class="required">*</span>', ['class' => 'control-label col-md-3 col-sm-3 col-xs-12'])) !!}
	<div class="col-md-6 col-sm-6 col-xs-12">
		{!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray() : null,  ['class' => 'select2_multiple form-control', 'multiple']) !!}
	</div>
    @if ($errors->has('roles')) <p class="help-block">{{ $errors->first('roles') }}</p> @endif
</div>

<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ])
@endif

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit User ' . $user->first_name)
@section('breadcrumb', 'Edit')
@section('breadcrumbSmall', 'User')

@section('content')
	
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Form Users</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li style="float:right;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					
					<!-- CODE HERE -->
					{!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update',  $user->id ], 'class' => 'form-horizontal form-label-left' ]) !!}
						@include('user._form')
						<!-- Submit Form Button -->
						<div class="ln_solid"></div>
						<div class="form-group">
							<div class="col-md-9 text-right">
								<a class="btn btn-danger" href="{{ route('users.index') }}">Cancel</a>
								{!! Form::submit('Save Changes', ['class' => 'btn btn-success']) !!}
							</div>
						</div>
					{!! Form::close() !!}
					
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Users')
@section('breadcrumb', 'Users')
@section('breadcrumbSmall', '')

@section('content')
	
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>List Data</h2>
					<ul class="nav navbar-right panel_toolbox">
						@can('add_users')
						<li>
							<a href="{{ route('users.create') }}" style="color: #1ABB9C;font-weight: bold;">
								<i class="fa fa-plus-square"></i> tambah user
							</a>
						</li>
						<li><a style="cursor: default;">|</a></li>
						@endcan
						<li style="float:right;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					
					<!-- CODE HERE -->
					<table class="table table-striped table-bordered table-hover" id="dTUser">
						<thead>
							<tr>
								<th>Nama</th>
								<th>NIP</th>
								<th>Jabatan</th>
								<th>Status</th>
								@can('edit_users', 'delete_users')
								<th class="text-center">Actions</th>
								@endcan
							</tr>
						</thead>
					</table>
					
				</div>
			</div>
		</div>
	</div>
@endsection

@section('footer_scripts')
<script>
	$(document).ready(function () {
		
        $('#dTUser').DataTable({
            "processing": true,
            "serverSide": true,
			"pageLength": 10,
            "ajax":{
                     "url": "{{ route('getDataUser') }}",
                     "dataType": "json",
                     "type": "POST",
                     "data":{ _token: "{{csrf_token()}}"}
                   },
            "columns": [
                { "data": "name" },
                { "data": "nip" },
                { "data": "json_data.jabatan" },
				{ "data": "active",
					"render":function(data, type, full, meta){
						$arr = ['Tidak Aktif', 'Aktif'];
					   return $arr[full.active];
					}
				},
                { "data": "id",
					"render":function(data, type, full, meta){
						var $x = full.id;
					   return '@include("shared._actions", ["entity" => "users", "id" => 3 ])';
					}
				}
            ]
        });
    });
</script>
@endsection

resources/views/user/new.blade.php
@extends('layouts.app')

@section('title', 'Create Users')
@section('breadcrumb', 'Create')
@section('breadcrumbSmall', 'Users')

@section('content')
	
	<div class="row">
		<div class="col-md-12 col-sm-12 col-xs-12">
			<div class="x_panel">
				<div class="x_title">
					<h2>Form Users</h2>
					<ul class="nav navbar-right panel_toolbox">
						<li style="float:right;"><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
					</ul>
					<div class="clearfix"></div>
				</div>
				<div class="x_content">
					
					<!-- CODE HERE -->
					{!! Form::open(['route' => ['users.store'], 'class' => 'form-horizontal form-label-left' ]) !!}
						@include('user._form')
						<!-- Submit Form Button -->
						<div class="ln_solid"></div>
						<div class="form-group">
							<div class="col-md-9 text-right">
								<a class="btn btn-danger" href="{{ route('users.index') }}">Cancel</a>
								{!! Form::submit('Create', ['class' => 'btn btn-success']) !!}
							</div>
						</div>
					{!! Form::close() !!}
					
				</div>
			</div>
		</div>
	</div>
@endsection